### ISSUE TITLE
Error: 不支持的field类型 undefined

### ISSUE THREAD

**Issue by clabnet** [lljj-x/vue-json-schema-form#219]
Unfortunately, the message not provide **what** field is not supported.
It is not useful to solve the problem without the field name where was found the issue.

```
vue3-form-naive.esm.min.js:4 Uncaught (in promise) Error: 不支持的field类型 undefined
    at gt (vue3-form-naive.esm.min.js:4:122958)
    at Proxy.<anonymous> (vue3-form-naive.esm.min.js:4:163971)
    at renderComponentRoot (runtime-core.esm-bundler.js:896:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5651:34)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
    at instance.update (runtime-core.esm-bundler.js:5694:56)
    at updateComponent (runtime-core.esm-bundler.js:5519:26)
    at processComponent (runtime-core.esm-bundler.js:5452:13)
    at patch (runtime-core.esm-bundler.js:5038:21)
    at patchKeyedChildren (runtime-core.esm-bundler.js:5814:17)
...
```

**Comment by lljj-x** [comment]
Custom widgets can be used.

Reference: https://vue-json-schema-form.lljj.me/zh/guide/adv-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89widget

**Comment by shurong2199** [comment]
遇到了同样的问题，猜测与 vue.config.js 配置中使用了 unplugin-auto-import/webpack 有关：

```
const AutoImport = require('unplugin-auto-import/webpack');
const Components = require('unplugin-vue-components/webpack');
const { ElementPlusResolver } = require('unplugin-vue-components/resolvers');
const { VueAmapResolver } = require('@vuemap/unplugin-resolver');

const path = require('path');

function resolve(dir) {
  return path.join(__dirname, dir);
}

module.exports = {
  runtimeCompiler: false,
  productionSourceMap: false,
  transpileDependencies: ['@lljj/vue-json-schema-form'],

  css: {
    loaderOptions: {
      sass: {
        prependData: `@use "@/styles/variables.scss" as *;`,
      },
    },
  },

  configureWebpack: (config) => {
    config.devtool = 'source-map';
    config.plugins = [
      ...config.plugins,
      AutoImport({
        imports: ['vue'],
        resolvers: [
          ElementPlusResolver({
            exclude: /^ElAmap[A-Z]*/,
          }),
          VueAmapResolver(),
        ],
        dts: './src/typings/auto-imports.d.ts',
        eslintrc: {
          enabled: true,
          filepath: './.eslintrc-auto-import.json',
          globalsPropValue: true,
        },
      }),
      Components({
        resolvers: [
          ElementPlusResolver({
            exclude: /^ElAmap[A-Z]*/,
          }),
          VueAmapResolver(),
        ],
        dts: './src/typings/components.d.ts',
      }),
    ];
    config.resolve.alias = {
      ...config.resolve.alias,
      Vue: 'vue',
    };
  },
};
````

**Comment by shurong2199** [comment]
复现同样的报错，原因是装错了依赖：
我的环境是 vue3 + element-plus，应该装  @lljj/vue3-form-element，但装成了 @lljj/vue-json-schema-form，引起以上报错。

替换成 @lljj/vue3-form-element 后，报错消失。

**Comment by shurong2199** [comment]
还有一种情况，是误把 Playground 的生成的 json 直接当成了 schema 的使用也会报以上错误。
如果把 Playground 生成的 json 赋值给 playgroundSchema，则应该写成：
`<vue-form :schema="playgroundSchema.schema"></vue-form>`
而不是 `<vue-form :schema="playgroundSchema"></vue-form>`
