### ISSUE TITLE
can't run 

### ISSUE THREAD

**Issue by edgardong** [lljj-x/vue-json-schema-form#60]
Cannot find module './lib/assign'

> Error: Cannot find module './lib/assign'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/donghao/study/vue-json-schema-form/packages/demo/demo-v2/node_modules/yargs/yargs.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /usr/local/lib/node_modules/yarn/lib/cli.js dev
Directory: /Users/donghao/study/vue-json-schema-form/packages/demo/demo-v2
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

how to resolve, please ?

**Comment by edgardong** [comment]
emm ....
好像要按照要求使用yarn 来安装，npm会有问题，
我是这样操作了，然后可以跑起来了
